
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IREOService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://59.144.167.68:9100/IREOService.svc?singleWsdl")
public class IREOService
    extends Service
{

    private final static URL IREOSERVICE_WSDL_LOCATION;
    private final static WebServiceException IREOSERVICE_EXCEPTION;
    private final static QName IREOSERVICE_QNAME = new QName("http://tempuri.org/", "IREOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://59.144.167.68:9100/IREOService.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IREOSERVICE_WSDL_LOCATION = url;
        IREOSERVICE_EXCEPTION = e;
    }

    public IREOService() {
        super(__getWsdlLocation(), IREOSERVICE_QNAME);
    }

    public IREOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IREOSERVICE_QNAME, features);
    }

    public IREOService(URL wsdlLocation) {
        super(wsdlLocation, IREOSERVICE_QNAME);
    }

    public IREOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IREOSERVICE_QNAME, features);
    }

    public IREOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IREOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IService1
     */
    @WebEndpoint(name = "BasicHttpBinding_IService1")
    public IService1 getBasicHttpBindingIService1() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IService1"), IService1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IService1
     */
    @WebEndpoint(name = "BasicHttpBinding_IService1")
    public IService1 getBasicHttpBindingIService1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IService1"), IService1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IREOSERVICE_EXCEPTION!= null) {
            throw IREOSERVICE_EXCEPTION;
        }
        return IREOSERVICE_WSDL_LOCATION;
    }

}
