
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
   // com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @param transID
     * @param utilityID
     * @param userName
     * @param billHistoryNo
     * @param meterID
     * @param password
     * @param transDateTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BillData", action = "http://tempuri.org/IService1/BillData")
    @WebResult(name = "BillDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BillData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BillData")
    @ResponseWrapper(localName = "BillDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BillDataResponse")
    public String billData(
        @WebParam(name = "TransID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "TransDateTime", targetNamespace = "http://tempuri.org/")
        String transDateTime,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "UtilityID", targetNamespace = "http://tempuri.org/")
        Long utilityID,
        @WebParam(name = "MeterID", targetNamespace = "http://tempuri.org/")
        String meterID,
        @WebParam(name = "BillHistoryNo", targetNamespace = "http://tempuri.org/")
        String billHistoryNo);

    /**
     * 
     * @param transID
     * @param utilityID
     * @param userName
     * @param argToDate
     * @param meterID
     * @param password
     * @param argFromDate
     * @param transDateTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DailyData", action = "http://tempuri.org/IService1/DailyData")
    @WebResult(name = "DailyDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DailyData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DailyData")
    @ResponseWrapper(localName = "DailyDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DailyDataResponse")
    public String dailyData(
        @WebParam(name = "TransID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "TransDateTime", targetNamespace = "http://tempuri.org/")
        String transDateTime,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "UtilityID", targetNamespace = "http://tempuri.org/")
        Long utilityID,
        @WebParam(name = "MeterID", targetNamespace = "http://tempuri.org/")
        String meterID,
        @WebParam(name = "ArgFromDate", targetNamespace = "http://tempuri.org/")
        String argFromDate,
        @WebParam(name = "ArgToDate", targetNamespace = "http://tempuri.org/")
        String argToDate);

    /**
     * 
     * @param transID
     * @param utilityID
     * @param userName
     * @param argToDate
     * @param meterID
     * @param password
     * @param argFromDate
     * @param transDateTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InstantData", action = "http://tempuri.org/IService1/InstantData")
    @WebResult(name = "InstantDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InstantData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InstantData")
    @ResponseWrapper(localName = "InstantDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InstantDataResponse")
    public String instantData(
        @WebParam(name = "TransID", targetNamespace = "http://tempuri.org/")
        String transID,
        @WebParam(name = "TransDateTime", targetNamespace = "http://tempuri.org/")
        String transDateTime,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "UtilityID", targetNamespace = "http://tempuri.org/")
        Long utilityID,
        @WebParam(name = "MeterID", targetNamespace = "http://tempuri.org/")
        String meterID,
        @WebParam(name = "ArgFromDate", targetNamespace = "http://tempuri.org/")
        String argFromDate,
        @WebParam(name = "ArgToDate", targetNamespace = "http://tempuri.org/")
        String argToDate);

}
