package com.bcits.bfm.service.billingCollectionManagement;

import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.servlet.http.HttpServletResponse;

import com.bcits.bfm.model.AdjustmentCalcLinesEntity;
import com.bcits.bfm.model.PaymentAdjustmentEntity;
import com.bcits.bfm.model.Property;
import com.bcits.bfm.service.GenericService;

public interface AdjustmentService extends GenericService<PaymentAdjustmentEntity> {

	List<PaymentAdjustmentEntity> findAll();

	void setAdjustmentStatus(int adjustmentId, String operation, HttpServletResponse response);

	void setStatusApproved(HttpServletResponse response);

	List<PaymentAdjustmentEntity> getAdjustmentId();

	List<AdjustmentCalcLinesEntity> getAdjusmentCalcItemList(int adjustmentId,String transactionCode);

	void setStatusPostedLedger(int adjustmentId, HttpServletResponse response);

	List<?> getAllPaidAccountNumbers();

	List<PaymentAdjustmentEntity> getAllAdjustmentByAccountId(int accountId,String adjustmentLedger);

	Set<String> commonFilterForAccountNumbersAdjustmentUrl();

	List<Integer> checkForNotPostedAdjustmentsAccountsIn(int accountId);
	
   List<Map<String, Object>> getTallyAdjustmentDetailData(int adjustmentId);
   
   void updateTallyStatus(int adjustmentId);

   List<PaymentAdjustmentEntity> searchAdjustmentDataByMonth(Date fromDateVal,Date toDateVal);

   int autoGeneratedAdjustmentNumber();
   
   int getAccountIdByPropertyId(int propertyId,String serviceType);
   
   List<Property> getPropertyByBlockId(int blockId);
   
   List<Integer> getAllBlocksId();
   
   void updateAdjustmentTallyStatus(int adjustmentId);
   
	public List<PaymentAdjustmentEntity> getAllDataXMl(java.util.Date monthDate);
   
	public String getAdjustmentStatus(int accountId,java.sql.Date currentbilldate,java.sql.Date preBillDate);

}
